// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	basic "github.com/pjimming/zeus/core/internal/handler/basic"
	"github.com/pjimming/zeus/core/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/ping",
				Handler: basic.PingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/login/user",
				Handler: basic.LoginUserHandler(serverCtx),
			},
		},
	)
}
