// Code generated by goctl. DO NOT EDIT.
package types

type LoginUserReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Username string `json:"username"`
	Token    string `json:"token"`
}
