// Code generated by goctl. DO NOT EDIT.
package types

type CreateUserReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email,optional"`
}

type UserResp struct {
	ID       int64  `json:"id"`
	Identity string `json:"identity"`
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}
